export type Product = { id: string; slug: string; title: string; description: string; price: number; saleActive: boolean; salePrice: number | null; category: string; tags: string[]; image: string; inventory: number; active: boolean; featured?: boolean; };
export type CartItemInput = { productId: string; quantity: number };
export type OrderStatus = 'pending_payment' | 'paid' | 'fulfilled' | 'canceled' | 'refund_pending' | 'partially_refunded' | 'refunded' | 'refund_failed';
export type Order = {
  id: string;
  email: string;
  customerName?: string;
  shippingAddress?: string;
  items: Array<{ productId: string; title: string; price: number; quantity: number }>;
  subtotal: number;
  shippingCost: number;
  total: number;
  status: OrderStatus;
  stripeSessionId?: string;
  stripePaymentIntentId?: string;
  stripeRefundId?: string;
  refundedAmount: number;
  refundReason?: string;
  canceledAt?: string;
  refundedAt?: string;
  createdAt: string;
};
export type MarketingSubscriberStatus = 'subscribed' | 'unsubscribed';
export type MarketingSubscriber = {
  id: string;
  email: string;
  name?: string;
  status: MarketingSubscriberStatus;
  source: string;
  couponCode: string;
  unsubscribeToken: string;
  consentedAt: string;
  unsubscribedAt?: string;
  createdAt: string;
  updatedAt: string;
};
export type FaqItem = {
  id: string;
  question: string;
  answer: string;
  sortOrder: number;
  active: boolean;
  createdAt: string;
  updatedAt: string;
};
export type BlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  published: boolean;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
};
export type CheckoutInput = { email: string; customerName: string; shippingAddress: string; items: CartItemInput[] };
export type MarketingSubscribeInput = { email: string; name?: string; source: string; couponCode: string };
export type FaqItemInput = { id?: string; question: string; answer: string; sortOrder: number; active: boolean };
export type BlogPostInput = { id?: string; slug: string; title: string; excerpt: string; body: string; published: boolean; publishedAt?: string | null };
export type Store = {
  listProducts(): Promise<Product[]>;
  listAdminProducts(): Promise<Product[]>;
  getProduct(slug: string): Promise<Product | undefined>;
  upsertProduct(product: Product): Promise<Product>;
  updateProductImage(slug: string, image: string): Promise<Product | undefined>;
  listOrders(): Promise<Order[]>;
  listOrdersByEmail(email: string): Promise<Order[]>;
  getOrder(orderId: string): Promise<Order | undefined>;
  createOrder(input: CheckoutInput): Promise<Order>;
  recordCheckoutSession(orderId: string, stripeSessionId: string): Promise<Order | undefined>;
  markOrderPaid(orderId: string, payment?: { stripeSessionId?: string; stripePaymentIntentId?: string }): Promise<Order | undefined>;
  markOrderFulfilled(orderId: string): Promise<Order | undefined>;
  cancelOrder(orderId: string, reason?: string): Promise<Order | undefined>;
  markOrderRefundPending(orderId: string, refund: { amount: number; refundId?: string; reason?: string }): Promise<Order | undefined>;
  markOrderRefunded(orderId: string, refund: { amount: number; refundId?: string; reason?: string }): Promise<Order | undefined>;
  markOrderRefundFailed(orderId: string, refund: { refundId?: string; reason?: string }): Promise<Order | undefined>;
  subscribeMarketing(input: MarketingSubscribeInput): Promise<{ subscriber: MarketingSubscriber; created: boolean }>;
  listMarketingSubscribers(): Promise<MarketingSubscriber[]>;
  unsubscribeMarketing(token: string): Promise<MarketingSubscriber | undefined>;
  listFaqItems(options?: { includeInactive?: boolean }): Promise<FaqItem[]>;
  upsertFaqItem(input: FaqItemInput): Promise<FaqItem>;
  listBlogPosts(options?: { includeDrafts?: boolean }): Promise<BlogPost[]>;
  getBlogPost(slug: string, options?: { includeDrafts?: boolean }): Promise<BlogPost | undefined>;
  upsertBlogPost(input: BlogPostInput): Promise<BlogPost>;
};